[build-system]
requires = ["setuptools >= 40.9.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.isort]
profile = "black"
multi_line_output = 3
src_paths = ["lsqecc", "test"]

[tool.black]
line-length = 100

[tool.mypy]
ignore_missing_imports = True
exclude = debug/ 
